project_id = "ithspbabhmdntioslfqe"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[functions.newsletter-subscribe]
verify_jwt = false

[functions.newsletter-unsubscribe]
verify_jwt = false

[functions.update-site-stats]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.receive-email]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.ai-universal-processor]
verify_jwt = false

[functions.send-genie-welcome-email]
verify_jwt = false

[functions.analyze-medical-image]
verify_jwt = false